version: '3'
services:
  test-docker:
    container_name: "test-back-container"
    build:
     context: .
     target: ${mood}
    volumes:
    - './src:/app/src:ro'
    ports:
    - "4000:4000"
    env_file:
    - ./config/.env
    depends_on:
      - mongo-express
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
volumes:
  mongo-db: